plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.synzapp.backgroundtransfers'
version = '0.1.0'

android {
  namespace "com.synzapp.backgroundtransfers"

  defaultConfig {
    versionCode 1
    versionName '0.1.0'
  }
}

dependencies {
  implementation "androidx.work:work-runtime-ktx:2.9.1"
}
